import ReactEcs, { Button, Label, ReactEcsRenderer, UiEntity } from '@dcl/sdk/react-ecs'
import { Color4 } from '@dcl/sdk/math'
import { PlayerIdentityData, Transform, engine } from '@dcl/sdk/ecs'
import { BotState } from '../shared/schemas'
import { LOCATIONS, MISSIONS, WEAPONS, type Difficulty, type GameMode, type MissionId, type WeaponId } from '../shared/config'
import { GENERATED_MISSIONS } from '../shared/generatedMissions'
import { clientState, isServerAlive } from './state'
import { playUiHoverSound, playUiSelectSound, setStoryMusic } from './audio'
import { finishIntroCinematic } from './cinematic'
import { saveCampaignProgress } from './progressPersistence'
import { buySupply, deployBuild, fireWeapon, getLocalPlayerState, getMatchState, reloadWeapon, requestJoin, requestMission, requestRespawn, selectBuild, selectDifficulty, selectWeapon, throwBomb, toggleInventory, toggleMap, toggleScope, useInventoryItem } from './setup'

const c={panel:Color4.fromHexString('#080b0ee8'),soft:Color4.fromHexString('#171c21e6'),line:Color4.fromHexString('#dce4eaff'),white:Color4.fromHexString('#f3f6f7ff'),muted:Color4.fromHexString('#a7b0b6ff'),red:Color4.fromHexString('#e63232ff'),cyan:Color4.fromHexString('#24bce8ff'),blue:Color4.fromHexString('#2998d6ff'),amber:Color4.fromHexString('#f1ad35ff'),green:Color4.fromHexString('#46b86bff'),water:Color4.fromHexString('#55bdeaff')}
const panel={color:c.panel}
const border={borderColor:c.line,borderWidth:1}
const iconPath=(name:string)=>`images/ui/${name}.png`
function icon(name:string,size=24){return <UiEntity uiTransform={{width:size,height:size,pointerFilter:'none'}} uiBackground={{texture:{src:iconPath(name)},textureMode:'stretch'}}/>}
function assetIcon(src:string,size=24){return <UiEntity uiTransform={{width:size,height:size,pointerFilter:'none'}} uiBackground={{texture:{src},textureMode:'stretch'}}/>}
function time(ends:number){if(!ends)return'15:00';const s=Math.max(0,Math.ceil((ends-Date.now())/1000));return`${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}`}
function bar(iconName:string,label:string,value:number,color:Color4){const p=Math.max(0,Math.min(100,value));return <UiEntity uiTransform={{width:230,height:27,flexDirection:'row',alignItems:'center'}}>{icon(iconName,21)}<Label value={label} fontSize={13} color={c.white} uiTransform={{width:67,height:24,margin:'0 0 0 5px'}}/><UiEntity uiTransform={{width:102,height:12}} uiBackground={{color:Color4.fromHexString('#30353aff')}}><UiEntity uiTransform={{width:`${p}%`,height:12}} uiBackground={{color}}/></UiEntity><Label value={`${Math.round(value)}`} fontSize={13} color={c.white} uiTransform={{width:32,height:24,margin:'0 0 0 5px'}}/></UiEntity>}
function cardinal(deg:number){return['N','NE','E','SE','S','SW','W','NW'][Math.round(deg/45)%8]}
// v167: Big Map + Mini Map keep the v166 facing calibration, but reverse the turn direction.
// DCL heading increases opposite to the pre-rendered arrow frame order: at the verified Outpost-facing
// bridge heading this still resolves to the same correct frame, while avatar-left now becomes map-left.
function playerMapArrow(){return ((-Math.round(clientState.heading/45)+4)%8+8)%8}

function compass(){const h=Math.round(clientState.heading);const ticks=[-60,-30,0,30,60].map(o=>(h+o+360)%360);return <UiEntity uiTransform={{positionType:'absolute',position:{left:'50%',top:16},margin:'0 0 0 -280px',width:560,height:52,flexDirection:'column',alignItems:'center',...border}} uiBackground={panel}><UiEntity uiTransform={{width:540,height:28,flexDirection:'row',justifyContent:'space-between'}}>{ticks.map((v,i)=><Label value={i===2?`${cardinal(v)}  ${v}`:`${cardinal(v)} ${v}`} fontSize={i===2?17:13} color={i===2?c.red:c.muted} uiTransform={{width:100,height:28}}/>)}</UiEntity><UiEntity uiTransform={{width:8,height:8}} uiBackground={{color:c.red}}/></UiEntity>}

function clamp(value:number,min:number,max:number){return Math.max(min,Math.min(max,value))}
function mapBadge(id:string,name:string,x:number,z:number,color:Color4,mapWidth=825,mapHeight=686){const width=name.length>11?170:136,left=x/480*mapWidth-width/2,top=(480-z)/480*mapHeight-10;return <UiEntity uiTransform={{positionType:'absolute',position:{left,top},width,height:30,padding:3,flexDirection:'row',alignItems:'center',borderColor:color,borderWidth:2,zIndex:3}} uiBackground={panel}>{icon(id,22)}<Label value={name} fontSize={11} color={c.white} uiTransform={{width:width-30,height:24,margin:'0 0 0 3px'}}/></UiEntity>}
function enemyDotColor(bot:any){return bot.variant==='king-mutant'?c.red:bot.family==='mutant'?c.green:Color4.fromHexString('#080808ff')}
function worldEnemyDots(mapWidth:number,mapHeight:number,mini=false,self?:any,zoom=1){const out:any[]=[];for(const[,b,t]of engine.getEntitiesWith(BotState,Transform)){if(!b.active||b.hp<=0)continue;let left:number,top:number;if(mini&&self){left=mapWidth/2+(t.position.x-self.position.x)/480*(mapWidth*zoom)-4;top=mapHeight/2+(t.position.z-self.position.z)/480*(mapHeight*zoom)-4}else{left=t.position.x/480*mapWidth-4;top=t.position.z/480*mapHeight-4}if(left<-8||top<-8||left>mapWidth||top>mapHeight)continue;out.push(<UiEntity uiTransform={{positionType:'absolute',position:{left,top},width:9,height:9,borderColor:Color4.fromHexString('#ffffffff'),borderWidth:1,zIndex:5,pointerFilter:'none'}} uiBackground={{color:enemyDotColor(b)}}/>)}return out}
function worldPlayerDots(mapWidth:number,mapHeight:number,mini=false,self?:any,zoom=1){if(clientState.selectedMode==='pvp'||clientState.localSolo||!clientState.joined)return null;const out:any[]=[];for(const[,identity,t]of engine.getEntitiesWith(PlayerIdentityData,Transform)){if(!identity.address)continue;let left:number,top:number;if(mini&&self){left=mapWidth/2+(t.position.x-self.position.x)/480*(mapWidth*zoom)-5;top=mapHeight/2+(t.position.z-self.position.z)/480*(mapHeight*zoom)-5}else{left=t.position.x/480*mapWidth-5;top=t.position.z/480*mapHeight-5}if(left<-10||top<-10||left>mapWidth||top>mapHeight)continue;out.push(<UiEntity uiTransform={{positionType:'absolute',position:{left,top},width:11,height:11,borderColor:c.cyan,borderWidth:2,zIndex:6,pointerFilter:'none'}} uiBackground={{color:Color4.fromHexString('#ffffffff')}}/>)}return out}

function minimap(){
  const mapWidth=260,mapHeight=216,t=Transform.getOrNull(engine.PlayerEntity)
  if(clientState.insideOutpost){
    const left=t?clamp((t.position.x-52)/88*mapWidth-13,1,mapWidth-27):117
    const top=t?clamp((156-t.position.z)/88*mapHeight-13,1,mapHeight-27):95
    const arrow=playerMapArrow()
    const rooms=[['outpost','ATRIUM',96,112],['city','MISSION',104,101.75],['badge','BADGES',91.5,102.5],['camp','TRADER',105.5,118.25],['rifle','STORAGE',88,119.75],['arena','EXIT',96,126]] as const
    const nearest=t?rooms.reduce((best,current)=>Math.hypot(t.position.x-current[2],t.position.z-current[3])<Math.hypot(t.position.x-best[2],t.position.z-best[3])?current:best):rooms[0]
    return <UiEntity uiTransform={{positionType:'absolute',position:{right:18,bottom:18},width:260,height:216,overflow:'hidden',borderColor:c.cyan,borderWidth:2,zIndex:8}} uiBackground={{texture:{src:'images/outpost-interior-map.png'},textureMode:'stretch'}} onMouseDown={toggleMap}>
      <UiEntity uiTransform={{positionType:'absolute',position:{left,top},width:27,height:27,zIndex:7}} uiBackground={{texture:{src:iconPath(`player-arrow-${arrow}`)},textureMode:'stretch'}}/>
      <Label value={`OUTPOST L1  ${nearest[1]}  |  CLICK MAP`} fontSize={10} color={c.cyan} uiTransform={{positionType:'absolute',position:{left:0,bottom:0},width:260,height:26,padding:5,zIndex:9}} uiBackground={panel}/>
    </UiEntity>
  }
  // The minimap is literally the same full-map image and coordinate transform, only clipped around the player.
  // This avoids a second UV coordinate system drifting away from the verified large map.
  const zoom=3.7,fullW=mapWidth*zoom,fullH=mapHeight*zoom,u=t?clamp(t.position.x/480,0,1):.5,v=t?clamp(t.position.z/480,0,1):.5
  const imageLeft=mapWidth/2-u*fullW,imageTop=mapHeight/2-v*fullH
  const places=Object.entries(LOCATIONS),nearest=t?places.reduce((best,current)=>Math.hypot(t.position.x-current[1].x,t.position.z-current[1].z)<Math.hypot(t.position.x-best[1].x,t.position.z-best[1].z)?current:best):places[0]
  const venue=t&&Math.hypot(t.position.x-nearest[1].x,t.position.z-nearest[1].z)<78?nearest[1].name.toUpperCase():'WILDERNESS'
  return <UiEntity uiTransform={{positionType:'absolute',position:clientState.isMobile?{right:18,top:92}:{right:24,bottom:110},width:clientState.isMobile?260:248,height:clientState.isMobile?216:204,overflow:'hidden',borderColor:c.line,borderWidth:2,zIndex:8}} onMouseDown={toggleMap}>
      <UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:mapWidth,height:mapHeight,zIndex:1,pointerFilter:'none'}}><UiEntity uiTransform={{positionType:'absolute',position:{left:imageLeft,top:imageTop},width:fullW,height:fullH}} uiBackground={{texture:{src:'images/project-exodus-minimap-source.jpg'},textureMode:'stretch'}}/></UiEntity>
      {worldEnemyDots(mapWidth,mapHeight,true,t,zoom)}{worldPlayerDots(mapWidth,mapHeight,true,t,zoom)}
      <UiEntity uiTransform={{positionType:'absolute',position:{left:mapWidth/2-14,top:mapHeight/2-14},width:28,height:28,zIndex:7}} uiBackground={{texture:{src:iconPath(`player-arrow-${playerMapArrow()}`)},textureMode:'stretch'}}/>
      <Label value={`${venue}  |  CLICK FOR FULL MAP`} fontSize={10} color={c.cyan} uiTransform={{positionType:'absolute',position:{left:0,bottom:0},width:260,height:28,padding:6,zIndex:9}} uiBackground={panel}/>
  </UiEntity>
}
function fullMap(){
  if(!clientState.mapOpen)return null
  const mapWidth=825,mapHeight=686,t=Transform.getOrNull(engine.PlayerEntity),left=t?clamp(t.position.x/480*mapWidth-14,1,mapWidth-29):398,top=t?clamp(t.position.z/480*mapHeight-14,1,mapHeight-29):329,arrow=playerMapArrow()
  if(clientState.insideOutpost){
    const roomLeft=t?clamp((t.position.x-52)/88*mapWidth-15,1,mapWidth-31):398,roomTop=t?clamp((156-t.position.z)/88*mapHeight-15,1,mapHeight-31):329
    const rooms=[['outpost','COMMAND ATRIUM',96,112],['city','MISSION OPERATIONS',104,101.75],['badge','BADGE COLLECTION',91.5,102.5],['camp','TRADER AND SUPPLIES',105.5,118.25],['rifle','GEAR STORAGE',88,119.75],['arena','NORTH EXIT',96,126]] as const
    return <UiEntity uiTransform={{positionType:'absolute',position:{left:'50%',top:'50%'},margin:'-390px 0 0 -452px',width:904,height:780,padding:16,flexDirection:'column',alignItems:'center',borderWidth:0,zIndex:40}} uiBackground={{color:Color4.fromHexString('#07090cf2')}}><UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:904,height:780,zIndex:45,pointerFilter:'none'}} uiBackground={{texture:{src:'images/ui/exodus-expanded/big-map-frame.png'},textureMode:'stretch'}}/>
      <UiEntity uiTransform={{width:872,height:45,flexDirection:'row',justifyContent:'space-between'}}><Label value="PROJECT EXODUS  OUTPOST INTERIOR L1" fontSize={24} color={c.white} uiTransform={{width:650,height:40}}/><Button value="CLOSE" fontSize={13} color={c.white} uiTransform={{width:110,height:36,...border}} uiBackground={{color:c.red}} onMouseDown={toggleMap}/></UiEntity>
      <UiEntity uiTransform={{width:825,height:686,positionType:'relative',overflow:'hidden',borderColor:c.red,borderWidth:3,borderRadius:12}} uiBackground={{texture:{src:'images/outpost-interior-map.png'},textureMode:'stretch'}}>
        <Label value="N\nW  +  E\nS" fontSize={13} color={c.white} uiTransform={{positionType:'absolute',position:{left:10,top:10},width:72,height:66,padding:5,zIndex:4}} uiBackground={panel}/>
        <UiEntity uiTransform={{positionType:'absolute',position:{left:roomLeft,top:roomTop},width:31,height:31,zIndex:6}} uiBackground={{texture:{src:iconPath(`player-arrow-${arrow}`)},textureMode:'stretch'}}/>
      </UiEntity>
    </UiEntity>
  }
  // Full map always shows the complete Project Exodus world. Only the mini-map follows/zooms the player.
  const worldLeft=t?clamp(t.position.x/480*mapWidth-16,1,mapWidth-33):mapWidth/2-16
  const worldTop=t?clamp(t.position.z/480*mapHeight-16,1,mapHeight-33):mapHeight/2-16
  return <UiEntity uiTransform={{positionType:'absolute',position:{left:'50%',top:'50%'},margin:'-390px 0 0 -452px',width:904,height:780,padding:16,flexDirection:'column',alignItems:'center',borderWidth:0,zIndex:40}} uiBackground={{color:Color4.fromHexString('#07090cf2')}}><UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:904,height:780,zIndex:45,pointerFilter:'none'}} uiBackground={{texture:{src:'images/ui/exodus-expanded/big-map-frame.png'},textureMode:'stretch'}}/>
    <UiEntity uiTransform={{width:872,height:45,flexDirection:'row',justifyContent:'space-between'}}><Label value="PROJECT EXODUS · ISLAND MAP" fontSize={24} color={c.white} uiTransform={{width:650,height:40}}/><Button value="CLOSE" fontSize={13} color={c.white} uiTransform={{width:110,height:36,...border}} uiBackground={{color:c.red}} onMouseDown={toggleMap}/></UiEntity>
    <UiEntity uiTransform={{width:825,height:686,positionType:'relative',overflow:'hidden',borderColor:c.red,borderWidth:3,borderRadius:12}} uiBackground={{texture:{src:'images/project-exodus-minimap-source.jpg'},textureMode:'stretch'}}>
      {worldEnemyDots(mapWidth,mapHeight)}{worldPlayerDots(mapWidth,mapHeight)}
      <UiEntity uiTransform={{positionType:'absolute',position:{left:worldLeft,top:worldTop},width:32,height:32,zIndex:6}} uiBackground={{texture:{src:iconPath(`player-arrow-${arrow}`)},textureMode:'stretch'}}/>
      <Label value="N" fontSize={18} color={c.white} uiTransform={{positionType:'absolute',position:{left:mapWidth/2-12,top:8},width:24,height:24,zIndex:7}}/>
    </UiEntity>
  </UiEntity>
}

function enemyCounts(){let mutants=0,drones=0,kings=0;for(const [,bot] of engine.getEntitiesWith(BotState)){if(!bot.active||bot.hp<=0)continue;if(bot.variant==='king-mutant')kings++;else if(bot.family==='mutant')mutants++;else if(bot.family==='drone')drones++;}return {mutants,drones,kings}}
function mission(){const match=getMatchState(),counts=enemyCounts(),i=Math.max(0,Math.min(GENERATED_MISSIONS.length-1,clientState.missionAcceptedIndex>=0?clientState.missionAcceptedIndex:0)),gm=GENERATED_MISSIONS[i],loc=(LOCATIONS as any)[gm.place],complete=(match?.announcement??'').includes('COMPLETE');return <UiEntity uiTransform={{positionType:'absolute',position:clientState.isMobile?{left:18,top:190}:{left:16,top:258},width:318,height:198,padding:10,flexDirection:'column',borderColor:c.red,borderWidth:{left:2,top:1,right:1,bottom:1}}} uiBackground={panel}><Label value={`MISSION ${String(gm.id).padStart(3,'0')} — ${gm.name}`} fontSize={16} color={c.white} uiTransform={{width:308,height:30}}/><Label value={complete?'MISSION COMPLETE':`${gm.objective} • ${gm.difficulty} • ${loc.name}`} fontSize={complete?20:13} color={complete?c.green:c.cyan} uiTransform={{width:308,height:28}}/><Label value={gm.brief} fontSize={11} color={c.white} uiTransform={{width:308,height:70}}/><Label value={`HOSTILES  M ${counts.mutants}  D ${counts.drones}  K ${counts.kings}`} fontSize={14} color={c.red} uiTransform={{width:308,height:28}}/><Label value={`Memory ${clientState.missionMemoryFound}/${gm.memory} • Data RAM ${clientState.missionDataRamFound}/${gm.ram}`} fontSize={11} color={c.muted} uiTransform={{width:308,height:24}}/></UiEntity>}

function missionCompleteBanner(){const m=getMatchState(),num=Math.max(1,m?.threatLevel??1);if(!(m?.announcement??'').includes(`MISSION ${num} COMPLETE`))return null;return <UiEntity uiTransform={{positionType:'absolute',position:{left:'50%',top:'42%'},margin:'0 0 0 -430px',width:860,height:150,padding:'28px 22px 18px 22px',alignItems:'center',justifyContent:'center',borderWidth:0,zIndex:80}} uiBackground={{color:Color4.fromHexString('#08090bf5')}}><UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:860,height:150,zIndex:81,pointerFilter:'none'}} uiBackground={{texture:{src:'images/ui/exodus-expanded/mission-complete-frame.png'},textureMode:'stretch'}}/><Label value={`MISSION ${num} COMPLETE`} fontSize={48} color={c.red} uiTransform={{width:820,height:90}}/></UiEntity>}


function stat(iconName:string,text:string,width:number,color=c.white){return <UiEntity uiTransform={{width,height:32,flexDirection:'row',alignItems:'center'}}>{icon(iconName,25)}<Label value={text} fontSize={14} color={color} uiTransform={{width:width-29,height:30,margin:'0 0 0 4px'}}/></UiEntity>}
function matchInfo(){const m=getMatchState(),p=getLocalPlayerState();return <UiEntity uiTransform={{positionType:'absolute',position:clientState.isMobile?{right:24,top:20}:{right:24,top:20},width:418,height:42,padding:6,flexDirection:'row',justifyContent:'space-between',borderWidth:0,borderRadius:12}} uiBackground={panel}>{stat('players',`${m?.alivePlayers??0}`,74)}{stat('skull',`${p?.kills??0}`,68)}<Label value={`THREAT ${m?.threatLevel??0}`} fontSize={14} color={(m?.threatLevel??0)>0?c.red:c.white} uiTransform={{width:110,height:30}}/>{stat('clock',time(m?.endsAt??0),112)}</UiEntity>}
function survival(){const p=getLocalPlayerState();return <UiEntity uiTransform={{positionType:'absolute',position:clientState.isMobile?{right:18,top:342}:{right:18,top:78},width:252,height:92,padding:'14px 12px 8px 12px',flexDirection:'column',...border}} uiBackground={panel}>{bar('health','HEALTH',p?.hp??100,c.red)}{bar('stamina','STAMINA',p?.stamina??100,c.blue)}</UiEntity>}
function ammo(){const p=getLocalPlayerState();const w=WEAPONS[(p?.equippedWeapon as WeaponId)||'pulse-rifle'],mag=p?.[w.magazineField]??0,reserve=p?.[w.ammoField]??0,status=mag>0?w.fireMode:reserve>0?'RELOAD':'FIND\nAMMO',weaponIcon=w.id==='rail-pistol'?'pistol':w.id==='scattergun'?'shotgun':'rifle';return <UiEntity uiTransform={{positionType:'absolute',position:clientState.isMobile?{right:18,top:442}:{right:18,top:166},width:252,height:122,padding:'8px 10px',flexDirection:'column',borderWidth:0,borderRadius:12}} uiBackground={panel}><UiEntity uiTransform={{width:232,height:48,flexDirection:'row',alignItems:'center'}}><UiEntity uiTransform={{width:92,height:48,positionType:'relative'}}><UiEntity uiTransform={{positionType:'absolute',position:{left:9,top:11},width:74,height:42,pointerFilter:'none'}} uiBackground={{texture:{src:`images/ui/weapon-${weaponIcon}.png`},textureMode:'stretch'}}/></UiEntity><Label value={`${mag} | ${reserve}`} fontSize={20} color={mag>0?c.white:c.red} uiTransform={{width:92,height:40,margin:'0 0 0 3px'}}/><Label value={w.name.toUpperCase()} fontSize={10} color={c.muted} uiTransform={{width:59,height:32}}/></UiEntity><UiEntity uiTransform={{width:232,height:40,margin:'5px 0 0 0',flexDirection:'row',alignItems:'center'}}><Label value={status} fontSize={12} color={mag>0?c.muted:c.amber} textAlign="middle-center" uiTransform={{width:92,height:40}}/><Button value="E  RELOAD" fontSize={12} color={c.white} uiTransform={{width:128,height:30,margin:'3px 0 0 8px',borderWidth:0}} uiBackground={{color:c.red}} onMouseDown={reloadWeapon}/></UiEntity></UiEntity>}

function slot(number:string,iconName:string,label:string,sub:string,selected:boolean,onClick:()=>void){return <UiEntity uiTransform={{width:130,height:68,margin:'0 3px',positionType:'relative',flexDirection:'row',alignItems:'center',padding:5,borderColor:selected?c.white:c.muted,borderWidth:selected?3:1}} uiBackground={{color:selected?Color4.fromHexString('#30363ddd'):c.panel}} onMouseDown={onClick}><Label value={number} fontSize={13} color={c.white} uiTransform={{positionType:'absolute',position:{left:4,top:3},width:18,height:18}}/>{icon(iconName,42)}<Label value={`${label}\n${sub}`} fontSize={11} color={c.white} uiTransform={{width:72,height:52,margin:'0 0 0 5px'}}/></UiEntity>}
function weaponSlot(number:string,kind:'rifle'|'pistol'|'shotgun',label:string,sub:string,selected:boolean,onClick:()=>void){const weaponColor=kind==='pistol'?Color4.fromHexString('#39e66fff'):kind==='rifle'?Color4.fromHexString('#b72cffff'):Color4.fromHexString('#ffd226ff');return <UiEntity uiTransform={{width:130,height:68,margin:'0 3px',positionType:'relative',flexDirection:'column',alignItems:'center',padding:3,borderWidth:0}} uiBackground={{color:selected?Color4.fromHexString('#30363ddd'):c.panel}} onMouseDown={onClick}><Label value={number} fontSize={12} color={c.white} uiTransform={{positionType:'absolute',position:{left:4,top:3},width:18,height:18}}/>{assetIcon(`images/ui/weapon-${kind}.png`,53)}<Label value={`${label}  ${sub}`} fontSize={9} color={c.white} uiTransform={{width:120,height:15}}/></UiEntity>}
function lootSlot(number:string,src:string,label:string,sub:string,color:Color4,onClick:()=>void){return <UiEntity uiTransform={{width:130,height:68,margin:'0 3px',positionType:'relative',flexDirection:'row',alignItems:'center',padding:5,borderWidth:0}} uiBackground={panel} onMouseDown={onClick}><Label value={number} fontSize={12} color={c.white} uiTransform={{positionType:'absolute',position:{left:4,top:3},width:18,height:18}}/>{assetIcon(src,46)}<Label value={`${label}\n${sub}`} fontSize={10} color={c.white} uiTransform={{width:68,height:46,margin:'0 0 0 4px'}}/></UiEntity>}
function quickbar(){const p=getLocalPlayerState();return <UiEntity uiTransform={{positionType:'absolute',position:{left:'50%',bottom:clientState.isMobile?20:24},margin:'0 0 0 -405px',width:810,height:70,padding:5,flexDirection:'row',borderWidth:0}} uiBackground={panel}>{weaponSlot('1','rifle','RIFLE',`${p?.magazineRifle??0}/${p?.ammoRifle??0}`,p?.equippedWeapon==='pulse-rifle',()=>selectWeapon('pulse-rifle'))}{weaponSlot('2','pistol','PISTOL',`${p?.magazinePistol??0}/${p?.ammoPistol??0}`,p?.equippedWeapon==='rail-pistol',()=>selectWeapon('rail-pistol'))}{weaponSlot('3','shotgun','SHOTGUN',`${p?.magazineShotgun??0}/${p?.ammoShotgun??0}`,p?.equippedWeapon==='scattergun',()=>selectWeapon('scattergun'))}{lootSlot('4','images/loot-bomb.png','BOMB',`${p?.bombs??0}`,Color4.fromHexString('#b72cffff'),throwBomb)}{lootSlot('5','images/loot-medkit.png','MEDKIT',`${p?.medkits??0}`,c.red,()=>useInventoryItem('medkit'))}{lootSlot('6','images/loot-water.png','WATER',`${p?.water??0}`,c.blue,()=>useInventoryItem('water'))}</UiEntity>}
function crosshair(){return <UiEntity uiTransform={{positionType:'absolute',position:{left:'50%',top:'50%'},width:34,height:34,margin:'-17px 0 0 -17px',zIndex:30,pointerFilter:'none'}}><UiEntity uiTransform={{positionType:'absolute',position:{left:15,top:0},width:3,height:10}} uiBackground={{color:c.white}}/><UiEntity uiTransform={{positionType:'absolute',position:{left:15,bottom:0},width:3,height:10}} uiBackground={{color:c.white}}/><UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:15},width:10,height:3}} uiBackground={{color:c.white}}/><UiEntity uiTransform={{positionType:'absolute',position:{right:0,top:15},width:10,height:3}} uiBackground={{color:c.white}}/></UiEntity>}
function inventory(){
 if(!clientState.inventoryOpen)return null
 const p=getLocalPlayerState()
 const btn=(id:string,label:string,left:number,top:number,width:number,height:number,color:Color4,onClick:()=>void,fontSize=13)=>{const hover=clientState.hoveredMenuButton===id;return <Button value={label} fontSize={fontSize} color={c.white} uiTransform={{positionType:'absolute',position:{left,top},width,height,borderWidth:0,zIndex:104}} uiBackground={{color:hover?Color4.fromHexString('#000000b8'):Color4.fromHexString('#00000001')}} onMouseEnter={()=>{clientState.hoveredMenuButton=id;playUiHoverSound()}} onMouseLeave={()=>{if(clientState.hoveredMenuButton===id)clientState.hoveredMenuButton=''}} onMouseDown={()=>{playUiSelectSound();onClick()}}/>}
 // v223: Gear & Storage live UI fitted to the measured openings of the supplied frame.
 // The frame remains decorative only; all original inventory actions/state are preserved.
 return <UiEntity uiTransform={{positionType:'absolute',position:{left:'50%',top:'50%'},margin:'-290px 0 0 -338px',width:676,height:581,zIndex:100,pointerFilter:'block'}} uiBackground={{color:Color4.fromHexString('#00000000')}}><UiEntity uiTransform={{positionType:'absolute',position:{left:18,top:18},width:640,height:545,zIndex:100,pointerFilter:'none'}} uiBackground={{color:Color4.fromHexString('#24282eff')}}/><UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:676,height:581,zIndex:101,pointerFilter:'none'}} uiBackground={{texture:{src:'images/gear-storage-frame.png'},textureMode:'stretch'}}/>
   {/* Header */}
   <Label value="GEAR AND STORAGE" fontSize={22} color={c.white} uiTransform={{positionType:'absolute',position:{left:64,top:48},width:350,height:29,zIndex:103}}/>
   {btn('gear-close','CLOSE',528,42,102,42,c.red,toggleInventory,13)}

   {/* Loadout / ammunition: all copy stays inside the large upper opening. */}
   <Label value="LOADOUT / AMMUNITION" fontSize={15} color={c.white} uiTransform={{positionType:'absolute',position:{left:218,top:110},width:262,height:22,zIndex:103}}/>
   <Label value="BUILD MATERIALS  ∞" fontSize={13} color={Color4.fromHexString('#ffbd21ff')} uiTransform={{positionType:'absolute',position:{left:72,top:150},width:220,height:22,zIndex:103}}/>
   <Label value={`PULSE RIFLE   ${p?.magazineRifle??0} / ${p?.ammoRifle??0}`} fontSize={13} color={Color4.fromHexString('#cf36ffff')} uiTransform={{positionType:'absolute',position:{left:72,top:181},width:235,height:22,zIndex:103}}/>
   <Label value={`RAIL PISTOL   ${p?.magazinePistol??0} / ${p?.ammoPistol??0}`} fontSize={13} color={Color4.fromHexString('#3dff7bff')} uiTransform={{positionType:'absolute',position:{left:350,top:150},width:220,height:22,zIndex:103}}/>
   <Label value={`SCATTERGUN   ${p?.magazineShotgun??0} / ${p?.ammoShotgun??0}`} fontSize={13} color={Color4.fromHexString('#ffd226ff')} uiTransform={{positionType:'absolute',position:{left:350,top:181},width:220,height:22,zIndex:103}}/>

   {/* Bomb row */}
   <UiEntity uiTransform={{positionType:'absolute',position:{left:61,top:268},width:39,height:39,zIndex:103}} uiBackground={{texture:{src:'images/loot-bomb.png'},textureMode:'stretch'}}/>
   <Label value={`BOMBS  ${p?.bombs??0}   •   Timed blast · 8 m radius`} fontSize={12} color={c.white} uiTransform={{positionType:'absolute',position:{left:112,top:275},width:286,height:27,zIndex:103}}/>
   {btn('gear-bomb','THROW BOMB',431,264,190,45,Color4.fromHexString('#7126aaff'),throwBomb,13)}

   {/* Consumables: quantity and action are centered as one visual unit in each colored block. */}
   <Label value={`MEDKITS  ${p?.medkits??0}`} fontSize={11} color={c.white} uiTransform={{positionType:'absolute',position:{left:58,top:337},width:162,height:20,zIndex:103}}/>
   <Label value={`SHIELD CELLS  ${p?.shieldCells??0}`} fontSize={11} color={c.white} uiTransform={{positionType:'absolute',position:{left:257,top:337},width:160,height:20,zIndex:103}}/>
   <Label value={`WATER  ${p?.water??0}`} fontSize={11} color={c.white} uiTransform={{positionType:'absolute',position:{left:454,top:337},width:162,height:20,zIndex:103}}/>
   {btn('gear-medkit','USE MEDKIT',53,379,172,47,c.red,()=>useInventoryItem('medkit'),12)}
   {btn('gear-shield','USE SHIELD CELL',254,379,166,47,Color4.fromHexString('#248dcfff'),()=>useInventoryItem('shield-cell'),12)}
   {btn('gear-water','DRINK WATER',447,379,174,47,Color4.fromHexString('#37b66bff'),()=>useInventoryItem('water'),12)}

   {/* Archive / life-credit row */}
   <Label value={`MEMORY PACKS  ${clientState.memoryPacksCollected}     DATA RAM  ${clientState.dataRamsCollected}`} fontSize={12} color={c.cyan} uiTransform={{positionType:'absolute',position:{left:61,top:487},width:314,height:24,zIndex:103}}/>
   <Label value={`LIFE CREDITS  ${p?.lifeCredits??0}`} fontSize={11} color={Color4.fromHexString('#df9bffff')} uiTransform={{positionType:'absolute',position:{left:413,top:488},width:102,height:22,zIndex:103}}/>
   {btn('gear-life','RESTORE HEALTH',518,480,100,38,Color4.fromHexString('#7130a0ff'),()=>useInventoryItem('life-credit'),9)}
 </UiEntity>
}
function terminalMissionId(place:string):MissionId{return place==='arena'?'reach-arena':place==='docks'?'reach-docks':'reach-city'}
function missionTerminal(){
 if(!clientState.missionTerminalOpen)return null
 const pageSize=8,totalPages=Math.ceil(GENERATED_MISSIONS.length/pageSize),page=Math.max(0,Math.min(totalPages-1,clientState.missionTerminalPage)),start=page*pageSize
 const visible=GENERATED_MISSIONS.slice(start,start+pageSize)
 const i=Math.max(0,Math.min(GENERATED_MISSIONS.length-1,clientState.missionTerminalSelected)),m=GENERATED_MISSIONS[i],loc=(LOCATIONS as any)[m.place],counts=enemyCounts(),accepted=clientState.missionAcceptedIndex===i
 const completedCount=clientState.completedGeneratedMissions.size
 const eligibleMemory=Array.from({length:10},(_,n)=>n+1).find(id=>completedCount>=id*5&&!clientState.collectedMemoryIds.has(id))
 const missedRam=!clientState.collectedDataRamIds.has(1)
 const availableMemory=eligibleMemory?1:0,availableRam=m.ram+(m.id>1&&missedRam?1:0)
 const foundMemory=clientState.missionMemoryFound,foundRam=clientState.missionDataRamFound
 const px=loc.x/480*620-13,py=(480-loc.z)/480*516-13,enemiesDone=counts.mutants+counts.drones+counts.kings===0
 const completed=clientState.completedGeneratedMissions.has(m.id)
 return <UiEntity uiTransform={{positionType:'absolute',position:{left:'50%',top:'50%'},margin:'-450px 0 0 -800px',width:1600,height:900,zIndex:95}} uiBackground={{color:Color4.fromHexString('#00000000')}}>
   <UiEntity uiTransform={{positionType:'absolute',position:{left:24,top:24},width:1552,height:852,zIndex:95,pointerFilter:'none'}} uiBackground={{color:Color4.fromHexString('#24282eff')}}/>
   <UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:1600,height:900,zIndex:96,pointerFilter:'none'}} uiBackground={{texture:{src:'images/mission-terminal-frame.png'},textureMode:'stretch'}}/>
   <Label value="MISSION TERMINAL — 100 GENERATED OPERATIONS" fontSize={24} color={c.white} uiTransform={{positionType:'absolute',position:{left:92,top:32},width:920,height:54,zIndex:97}}/>
   <Label value="STORY-SAFE ARCHIVE RECOVERY" fontSize={13} color={c.cyan} uiTransform={{positionType:'absolute',position:{left:1120,top:39},width:250,height:42,zIndex:97}}/>
   <Button value="CLOSE" fontSize={14} color={c.white} uiTransform={{positionType:'absolute',position:{left:1400,top:27},width:155,height:67,borderWidth:0,zIndex:98}} uiBackground={{color:Color4.fromHexString('#00000001')}} onMouseEnter={()=>playUiHoverSound()} onMouseDown={()=>{playUiSelectSound();clientState.missionTerminalOpen=false}}/>

   <UiEntity uiTransform={{positionType:'absolute',position:{left:54,top:133},width:490,height:680,padding:12,flexDirection:'column',zIndex:97}}>
    <Label value={`AVAILABLE MISSIONS  ${start+1}-${Math.min(start+pageSize,100)} / 100`} fontSize={18} color={c.white} uiTransform={{width:466,height:32}}/>
    {visible.map((x,n)=>{const idx=start+n;const done=clientState.completedGeneratedMissions.has(x.id);const mem=eligibleMemory?1:0,ram=x.ram+(x.id>1&&missedRam?1:0);return <Button value={`${done?'✓ ':''}${String(x.id).padStart(3,'0')}  ${x.name}\n${(LOCATIONS as any)[x.place].name.toUpperCase()}   ${x.objective}   ${x.difficulty}   ${mem} MP / ${ram} RAM`} fontSize={10} color={c.white} uiTransform={{width:466,height:67,margin:'0 0 5px 0',borderColor:idx===i?c.red:c.muted,borderWidth:idx===i?2:1}} uiBackground={{color:idx===i?Color4.fromHexString('#501018dd'):Color4.fromHexString('#090c12d9')}} onMouseEnter={()=>playUiHoverSound()} onMouseDown={()=>{playUiSelectSound();clientState.missionTerminalSelected=idx}}/>})}
    <UiEntity uiTransform={{width:466,height:48,flexDirection:'row',justifyContent:'space-between'}}><Button value="◀ PREV" fontSize={11} color={c.white} uiTransform={{width:135,height:38,...border}} uiBackground={{color:c.soft}} onMouseDown={()=>{playUiSelectSound();clientState.missionTerminalPage=Math.max(0,page-1)}}/><Label value={`PAGE ${page+1}/${totalPages}`} fontSize={11} color={c.cyan} uiTransform={{width:150,height:38}}/><Button value="NEXT ▶" fontSize={11} color={c.white} uiTransform={{width:135,height:38,...border}} uiBackground={{color:c.soft}} onMouseDown={()=>{playUiSelectSound();clientState.missionTerminalPage=Math.min(totalPages-1,page+1)}}/></UiEntity>
   </UiEntity>

   <UiEntity uiTransform={{positionType:'absolute',position:{left:608,top:137},width:405,height:405,padding:14,flexDirection:'column',zIndex:97}}>
    <Label value={`${String(m.id).padStart(3,'0')} — ${m.name}`} fontSize={19} color={c.cyan} uiTransform={{width:377,height:38}}/>
    <Label value={`${m.objective}  •  ${m.difficulty}  •  ${m.enemySet}`} fontSize={11} color={m.difficulty==='HARD'||m.difficulty==='SPECIAL'?c.red:m.difficulty==='MEDIUM'?c.amber:c.green} uiTransform={{width:377,height:30}}/>
    <Label value={m.brief} fontSize={12} color={c.white} uiTransform={{width:377,height:90}}/>
    <Label value="OBJECTIVES" fontSize={14} color={c.red} uiTransform={{width:377,height:26}}/>
    <Label value={`${accepted?'☑':'□'} Reach ${loc.name}\n${enemiesDone?'☑':'□'} ${m.objective}: clear required hostiles\n${availableMemory?`${foundMemory>=availableMemory?'☑':'□'} Memory Packs ${foundMemory}/${availableMemory}`:'— Memory Packs 0 available'}\n${availableRam?`${foundRam>=availableRam?'☑':'□'} Data RAMs ${foundRam}/${availableRam}`:'— Data RAMs 0 available'}\n${completed?'☑':'□'} Complete / extract`} fontSize={12} color={c.white} uiTransform={{width:377,height:126}}/>
   </UiEntity>

   <UiEntity uiTransform={{positionType:'absolute',position:{left:608,top:607},width:405,height:201,padding:14,flexDirection:'column',zIndex:97}}>
    <Label value={`OFFERED REWARDS\nBuild Materials ×${m.materials}   Bombs ×${m.bombs}\nShield Cells ×${m.shieldCells}${m.lifeCredits?`   Life Credits ×${m.lifeCredits}`:''}\n${completed?'REPLAY: repeatable resources only':'Unique collectibles/badges never duplicate'}`} fontSize={11} color={c.amber} uiTransform={{width:377,height:108}}/>
    <Button value={accepted?'MISSION ACTIVE':completed?'▶  REPLAY MISSION':'▶  ACCEPT MISSION'} fontSize={15} color={c.white} uiTransform={{width:377,height:48,borderColor:accepted?c.green:c.red,borderWidth:2}} uiBackground={{color:accepted?Color4.fromHexString('#13552dee'):c.red}} onMouseEnter={()=>playUiHoverSound()} onMouseDown={()=>{if(!accepted){playUiSelectSound();clientState.missionAcceptedIndex=i;clientState.missionMemoryFound=0;clientState.missionDataRamFound=0;clientState.missionTerminalOpen=false;saveCampaignProgress(true);requestMission(terminalMissionId(m.place))}}}/>
   </UiEntity>

   <UiEntity uiTransform={{positionType:'absolute',position:{left:1100,top:137},width:450,height:670,padding:12,flexDirection:'column',zIndex:97}}>
    <Label value={`MISSION MAP — ${loc.name.toUpperCase()}`} fontSize={17} color={c.white} uiTransform={{width:426,height:32}}/>
    <UiEntity uiTransform={{width:426,height:355,positionType:'relative',overflow:'hidden',borderColor:c.cyan,borderWidth:2}} uiBackground={{texture:{src:'images/project-exodus-minimap-source.jpg'},textureMode:'stretch'}}><UiEntity uiTransform={{positionType:'absolute',position:{left:Math.max(0,Math.min(398,loc.x/480*426-13)),top:Math.max(0,Math.min(327,(480-loc.z)/480*355-13))},width:28,height:28,borderColor:c.red,borderWidth:4,zIndex:4}} uiBackground={{color:Color4.fromHexString('#ff203080')}}/><Label value="MISSION" fontSize={9} color={c.white} uiTransform={{positionType:'absolute',position:{left:Math.max(0,Math.min(366,loc.x/480*426-33)),top:Math.max(0,Math.min(329,(480-loc.z)/480*355+17))},width:80,height:20,zIndex:5}}/></UiEntity>
    <Label value={`CHECKPOINT: ${loc.name}   X:${loc.x} Z:${loc.z}\nVALID PATH: ${m.reachable?'YES':'NO'} • generation checked.`} fontSize={11} color={c.cyan} uiTransform={{width:426,height:54,margin:'7px 0 0 0'}}/>
    <Label value="ARCHIVE RULES\nMemory Packs unlock in authored order every 5 successful missions. Earliest missed eligible pack is prioritized. Data RAM discoveries are unique; missed Data RAM 01 remains recoverable. Mission, archive and badge progress are tracked independently." fontSize={11} color={c.white} uiTransform={{width:426,height:115}}/>
   </UiEntity>
 </UiEntity>
}
function shop(){
 if(!clientState.shopOpen)return null
 const p:any=getLocalPlayerState(),earned=BADGES.filter(b=>badgeProgress(p,b)>=b[3]).length
 const tabs=[['browse','BROWSE BADGES'],['mine','MY BADGES'],['list','LIST A TRADE'],['listings','MY LISTINGS'],['requests','TRADE REQUESTS']] as const
 const status=clientState.traderTab==='browse'?'ALL 30 PROJECT EXODUS BADGES — select a badge to inspect trading status':clientState.traderTab==='mine'?`YOUR COLLECTION — ${earned}/30 badges unlocked`:clientState.traderTab==='list'?'CREATE TRADE — choose one unlocked badge to offer and the badge you want in return':clientState.traderTab==='listings'?'MY ACTIVE LISTINGS — local client listing interface ready for network persistence':'TRADE REQUESTS — accept/decline interface ready for multiplayer persistence'
 return <UiEntity uiTransform={{positionType:'absolute',position:{left:'50%',top:'50%'},margin:'-430px 0 0 -700px',width:1400,height:860,zIndex:90}} uiBackground={{color:Color4.fromHexString('#00000000')}}><UiEntity uiTransform={{positionType:'absolute',position:{left:20,top:20},width:1360,height:820,zIndex:90,pointerFilter:'none'}} uiBackground={{color:Color4.fromHexString('#24282eff')}}/><UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:1400,height:860,zIndex:91,pointerFilter:'none'}} uiBackground={{texture:{src:'images/trader-shop-frame.png'},textureMode:'stretch'}}/>
  <Label value={`TRADER SHOP — BADGE TRADING HUB   SEASON 1   ${earned}/30`} fontSize={23} color={c.white} uiTransform={{positionType:'absolute',position:{left:78,top:29},width:1080,height:45,zIndex:92}}/>
  <Button value="CLOSE" fontSize={13} color={c.white} uiTransform={{positionType:'absolute',position:{left:1221,top:28},width:132,height:48,borderWidth:0,zIndex:94}} uiBackground={{color:Color4.fromHexString('#00000001')}} onMouseEnter={()=>playUiHoverSound()} onMouseDown={()=>clientState.shopOpen=false}/>
  <UiEntity uiTransform={{positionType:'absolute',position:{left:48,top:102},width:1304,height:55,flexDirection:'row',justifyContent:'space-between',zIndex:93}}>{tabs.map(([id,label])=>{const hover=clientState.hoveredMenuButton===`trade-tab-${id}`;return <Button value={label} fontSize={11} color={c.white} uiTransform={{width:252,height:52,borderWidth:0}} uiBackground={{color:hover?Color4.fromHexString('#000000c8'):clientState.traderTab===id?Color4.fromHexString('#7b1018aa'):Color4.fromHexString('#00000001')}} onMouseEnter={()=>{clientState.hoveredMenuButton=`trade-tab-${id}`;playUiHoverSound()}} onMouseLeave={()=>{if(clientState.hoveredMenuButton===`trade-tab-${id}`)clientState.hoveredMenuButton=''}} onMouseDown={()=>{playUiSelectSound();clientState.traderTab=id}}/>})}</UiEntity>
  <Label value={status} fontSize={14} color={c.cyan} uiTransform={{positionType:'absolute',position:{left:70,top:158},width:1260,height:22,zIndex:92}}/>
  <UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:1400,height:860,zIndex:92}}>{BADGES.map((b,i)=>{const ok=badgeProgress(p,b)>=b[3],src=`images/badges/badge-${String(i+1).padStart(2,'0')}${ok?'':'-locked'}.png`;const col=i%8,row=Math.floor(i/8);const cellCentersX=[141,301,461,621,781,941,1101,1261],cellCentersY=[260,414,568,716];const cardW=126,cardH=122;const cellLeft=cellCentersX[col]-cardW/2,cellTop=cellCentersY[row]-cardH/2;return <UiEntity uiTransform={{positionType:'absolute',position:{left:cellLeft,top:cellTop},width:cardW,height:cardH,flexDirection:'column',alignItems:'center',justifyContent:'flex-start',borderWidth:0,zIndex:93}} uiBackground={{color:clientState.hoveredMenuButton===`trade-badge-${i}`?Color4.fromHexString('#000000b8'):Color4.fromHexString('#00000001')}} onMouseEnter={()=>{const id=`trade-badge-${i}`;if(clientState.hoveredMenuButton!==id){clientState.hoveredMenuButton=id;playUiHoverSound()}}} onMouseLeave={()=>{if(clientState.hoveredMenuButton===`trade-badge-${i}`)clientState.hoveredMenuButton=''}} onMouseDown={()=>{playUiSelectSound();clientState.traderSelectedBadge=i}}><UiEntity uiTransform={{width:84,height:84,margin:'0 0 0 0'}} uiBackground={{texture:{src},textureMode:'stretch'}}/><Label value={`${String(i+1).padStart(2,'0')} ${b[0]} ${ok?'OWNED':'LOCKED'}`} fontSize={5} color={ok?c.white:c.muted} uiTransform={{width:118,height:28,margin:'4px 0 0 0'}}/></UiEntity>})}</UiEntity>
  <Label value="Cross-player trade settlement requires the shared multiplayer persistence/backend; this UI never fabricates remote trades." fontSize={10} color={c.amber} uiTransform={{positionType:'absolute',position:{left:92,top:793},width:1215,height:22,zIndex:92}}/>
 </UiEntity>
}
function build(){const p=getLocalPlayerState();const b=(name:string,k:'wall'|'ramp'|'platform')=><Button value={name} fontSize={11} color={c.white} uiTransform={{width:72,height:24,margin:'0 4px',borderWidth:0,borderRadius:6}} uiBackground={{color:c.soft}} onMouseDown={()=>selectBuild(k)}/>;return <UiEntity uiTransform={{positionType:'absolute',position:{right:24,bottom:24},width:248,height:64,padding:4,flexDirection:'column',alignItems:'center',borderWidth:0}} uiBackground={{color:Color4.fromHexString('#00000000')}}><Label value="BUILD MATERIALS  ∞" fontSize={12} color={c.white} uiTransform={{width:240,height:22}}/><UiEntity uiTransform={{width:240,height:30,flexDirection:'row',alignItems:'center',justifyContent:'center'}}>{b('WALL','wall')}{b('RAMP','ramp')}{b('FLOOR','platform')}</UiEntity></UiEntity>}
function controls(){const p=getLocalPlayerState(),pistol=p?.equippedWeapon==='rail-pistol';return <UiEntity uiTransform={{positionType:'absolute',position:{right:20,top:337},width:220,height:112,padding:'2px 8px',flexDirection:'column',borderWidth:0,borderRadius:12}} uiBackground={{color:Color4.fromHexString('#00000000')}}><Button value="GAME CONTROLS" fontSize={13} color={c.white} uiTransform={{width:204,height:40,margin:'4px 0 0 0',borderWidth:0,borderRadius:8}} uiBackground={{color:Color4.fromHexString('#00000000')}} onMouseDown={()=>clientState.controlsOpen=!clientState.controlsOpen}/><Button value={clientState.scopeToggled?'EXIT SCOPE':'OPEN SCOPE'} fontSize={13} color={c.white} uiTransform={{width:204,height:40,margin:'14px 0 0 0',borderWidth:0,borderRadius:8}} uiBackground={{color:Color4.fromHexString('#00000000')}} onMouseDown={()=>{if(pistol){clientState.notification='SCOPE NOT AVAILABLE FOR PISTOL — CHANGE GUN AND SELECT SCOPE AGAIN';clientState.notificationUntil=Date.now()+3500}else toggleScope()}}/></UiEntity>}
function controlsOverlay(){if(!clientState.controlsOpen)return null;return <UiEntity uiTransform={{positionType:'absolute',position:{left:'50%',top:'50%'},margin:'-290px 0 0 -330px',width:660,height:580,padding:22,flexDirection:'column',alignItems:'center',...border,zIndex:70}} uiBackground={{color:Color4.fromHexString('#080b0ef5')}}><UiEntity uiTransform={{width:616,height:48,flexDirection:'row',justifyContent:'space-between'}}><Label value="PROJECT EXODUS — GAME CONTROLS" fontSize={23} color={c.white} uiTransform={{width:470,height:42}}/><Button value="CLOSE" fontSize={13} color={c.white} uiTransform={{width:110,height:38,...border}} uiBackground={{color:c.red}} onMouseDown={()=>clientState.controlsOpen=false}/></UiEntity><Label value="COMBAT" fontSize={16} color={c.red} uiTransform={{width:616,height:30}}/><Label value="LEFT CLICK   FIRE\nE   RELOAD\n1   RIFLE\n2   PISTOL\n3   SHOTGUN\n4   THROW BOMB" fontSize={15} color={c.white} uiTransform={{width:616,height:150}}/><Label value="MOVEMENT / WORLD" fontSize={16} color={c.cyan} uiTransform={{width:616,height:30}}/><Label value="W A S D   MOVE\nSPACE   JUMP\nE   RELOAD / INTERACT / PICK UP\nF   PLACE SELECTED BUILD MATERIAL\nENTER   CHAT\nCLICK MINIMAP   FULL MAP" fontSize={15} color={c.white} uiTransform={{width:616,height:150}}/><Label value="SCOPE: Use OPEN SCOPE below Game Controls with Rifle or Shotgun. Pistol does not support scope." fontSize={13} color={c.muted} uiTransform={{width:616,height:34}}/></UiEntity>}

function welcomeScreen(){
 if(!clientState.welcomeOpen)return null
 const now=Date.now(),loading=clientState.welcomeLoadingUntil>0,remaining=loading?Math.max(0,clientState.welcomeLoadingUntil-now):0
 if(loading&&remaining<=0){clientState.welcomeOpen=false;clientState.welcomeLoadingUntil=0;return null}
 const hover=clientState.hoveredMenuButton==='welcome-enter',pct=loading?Math.max(0,Math.min(100,Math.round((1-remaining/10000)*100))):0
 return <UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:1920,height:1080,zIndex:190,pointerFilter:'block'}} uiBackground={{texture:{src:'images/project-exodus-welcome.png'},textureMode:'stretch'}}>
   {hover&&<UiEntity uiTransform={{positionType:'absolute',position:{left:596,top:815},width:728,height:122,zIndex:191,pointerFilter:'none'}} uiBackground={{texture:{src:'images/ui/welcome-enter-hover.png'},textureMode:'stretch'}}/>}
   <Button value="" uiTransform={{positionType:'absolute',position:{left:596,top:815},width:728,height:122,zIndex:192,borderWidth:0}} uiBackground={{color:Color4.fromHexString('#00000001')}} onMouseEnter={()=>{if(clientState.hoveredMenuButton!=='welcome-enter'){clientState.hoveredMenuButton='welcome-enter';playUiHoverSound()}}} onMouseLeave={()=>{if(clientState.hoveredMenuButton==='welcome-enter')clientState.hoveredMenuButton=''}} onMouseDown={()=>{if(!loading){clientState.hoveredMenuButton='welcome-pressed';clientState.welcomeLoadingUntil=Date.now()+10000}}}/>
   
   {loading&&<UiEntity uiTransform={{positionType:'absolute',position:{left:610,top:925},width:700,height:92,zIndex:193,padding:12,flexDirection:'column',alignItems:'center'}} uiBackground={{color:Color4.fromHexString('#050505dd')}}><Label value={`INITIALIZING EXODUS  ${pct}%`} fontSize={20} color={c.white} uiTransform={{width:660,height:32}}/><UiEntity uiTransform={{width:660,height:28,borderColor:c.red,borderWidth:3}} uiBackground={{color:Color4.fromHexString('#180408ee')}}><UiEntity uiTransform={{width:`${pct}%`,height:22}} uiBackground={{color:Color4.fromHexString('#e9162fff')}}/></UiEntity></UiEntity>}
 </UiEntity>
}

function menuHotspot(label:string,subtitle:string,mode:GameMode,top:number,color:Color4){const id='mode-'+mode,hover=clientState.hoveredMenuButton===id;return <Button value="" fontSize={1} color={Color4.fromHexString('#ffffff00')} uiTransform={{positionType:'absolute',position:{left:645,top},width:634,height:82,borderColor:hover?color:Color4.fromHexString('#ffffff08'),borderWidth:hover?4:1,zIndex:24}} uiBackground={{color:hover?Color4.fromHexString('#141c26d8'):Color4.fromHexString('#00000001')}} onMouseEnter={()=>{if(clientState.hoveredMenuButton!==id){clientState.hoveredMenuButton=id;playUiHoverSound()}}} onMouseLeave={()=>{if(clientState.hoveredMenuButton===id)clientState.hoveredMenuButton=''}} onMouseDown={()=>{playUiSelectSound();requestJoin(mode)}}/>}
function menuDifficulty(value:Difficulty,left:number){const selected=clientState.difficulty===value,id='difficulty-'+value,hover=clientState.hoveredMenuButton===id;const color=value==='easy'?c.green:value==='normal'?c.amber:c.red;return <Button value="" uiTransform={{positionType:'absolute',position:{left,top:330},width:194,height:52,borderColor:(selected||hover)?color:Color4.fromHexString('#ffffff08'),borderWidth:(selected||hover)?4:1,zIndex:25}} uiBackground={{color:hover?Color4.fromHexString('#ffffff20'):Color4.fromHexString('#00000001')}} onMouseEnter={()=>{if(clientState.hoveredMenuButton!==id){clientState.hoveredMenuButton=id;playUiHoverSound()}}} onMouseLeave={()=>{if(clientState.hoveredMenuButton===id)clientState.hoveredMenuButton=''}} onMouseDown={()=>{playUiSelectSound();selectDifficulty(value)}}/>}
function lobby(){if(clientState.welcomeOpen||!clientState.insideOutpost||clientState.joining||clientState.joined)return null;return <UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:1920,height:1080,zIndex:20,pointerFilter:'block'}} uiBackground={{texture:{src:'images/project-exodus-opening-menu.png'},textureMode:'stretch'}}>
  {menuDifficulty('easy',663)}{menuDifficulty('normal',861)}{menuDifficulty('hard',1060)}
  {menuHotspot('SOLO SURVIVAL','EXPLORE • LOOT • SURVIVE','solo-bots',400,c.blue)}
  {menuHotspot('CO-OP TEAM VS HOSTILES','TEAM UP • FIGHT • SURVIVE','coop-bots',493,c.green)}
  {menuHotspot('PVP: SURVIVOR VS SURVIVOR','PLAYERS • COMPETE • DOMINATE','pvp',589,c.red)}
  {menuHotspot('PVPVE: PLAYERS + HOSTILES','UNPREDICTABLE • HIGH RISK • HIGH REWARD','pvp-bots',689,c.amber)}
  <Label value={isServerAlive()?'SECURE SERVER ONLINE  •  SELECT DEPLOYMENT':'SOLO FALLBACK AVAILABLE  •  SELECT DEPLOYMENT'} fontSize={12} color={isServerAlive()?c.green:c.amber} uiTransform={{positionType:'absolute',position:{left:760,top:1005},width:400,height:28,zIndex:26}}/>
</UiEntity>}
function enemyTarget(){if(!clientState.enemyTargetName)return null;const pct=Math.max(0,Math.min(100,clientState.enemyTargetHp/Math.max(1,clientState.enemyTargetMaxHp)*100));return <UiEntity uiTransform={{positionType:'absolute',position:{left:'50%',top:'58%'},margin:'0 0 0 -145px',width:330,height:70,padding:'15px 18px 10px 18px',flexDirection:'column',borderWidth:0}} uiBackground={{color:Color4.fromHexString('#08090bf2')}}><UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:330,height:70,zIndex:1,pointerFilter:'none'}} uiBackground={{texture:{src:'images/ui/exodus-expanded/enemy-health-frame.png'},textureMode:'stretch'}}/><Label value={clientState.enemyTargetName} fontSize={12} color={c.white} uiTransform={{width:294,height:18}}/><UiEntity uiTransform={{width:294,height:10}} uiBackground={{color:Color4.fromHexString('#34393eff')}}><UiEntity uiTransform={{width:`${pct}%`,height:10}} uiBackground={{color:c.red}}/></UiEntity></UiEntity>}
function droneAlert(){if(!clientState.droneAlert)return null;return <Label value={clientState.droneAlert} fontSize={18} color={c.red} uiTransform={{positionType:'absolute',position:{left:'50%',top:130},margin:'0 0 0 -250px',width:500,height:46,padding:10,borderColor:c.red,borderWidth:2}} uiBackground={panel}/>}
function damageIndicator(){const d=clientState.damageDirection;if(!d)return null;if(d==='LEFT')return <Label value="▲ LEFT" fontSize={24} color={c.red} uiTransform={{positionType:'absolute',position:{left:35,top:480},width:110,height:42,pointerFilter:'none'}}/>;if(d==='RIGHT')return <Label value="RIGHT ▲" fontSize={24} color={c.red} uiTransform={{positionType:'absolute',position:{right:35,top:480},width:110,height:42,pointerFilter:'none'}}/>;return <Label value={`▲ ${d}`} fontSize={24} color={c.red} uiTransform={{positionType:'absolute',position:d==='FRONT'?{left:'50%',top:115}:{left:'50%',bottom:120},margin:'0 0 0 -55px',width:110,height:42,pointerFilter:'none'}}/>}
function note(){const m=getMatchState(),text=clientState.notification||(clientState.joining?'Deployment selected - preparing loadout':m?.announcement||'');if(!text)return null;return <Label value={text} fontSize={14} color={c.white} uiTransform={{positionType:'absolute',position:{left:'50%',top:78},margin:'0 0 0 -250px',width:500,height:38,padding:8,...border}} uiBackground={panel}/>}
function mobile(){
 // v263: the redundant custom FIRE/RELOAD/weapon/build stack is removed on mobile.
 // Decentraland native mobile controls remain available; desktop behavior is untouched.
 return null
}

function elimination(){
  const p=getLocalPlayerState()
  if(!p||p.alive||clientState.eliminationDismissed)return null
  const solo=getMatchState()?.mode==='solo-bots'
  const hotspot=(id:string,left:number,top:number,width:number,height:number,onMouseDown:()=>void)=>{const hover=clientState.hoveredMenuButton===id;return <Button value="" fontSize={1} color={Color4.fromHexString('#ffffff00')} uiTransform={{positionType:'absolute',position:{left,top},width,height,borderColor:hover?c.red:Color4.fromHexString('#ffffff00'),borderWidth:hover?4:0,zIndex:52}} uiBackground={{color:hover?Color4.fromHexString('#ff1f3038'):Color4.fromHexString('#00000001')}} onMouseEnter={()=>{if(clientState.hoveredMenuButton!==id){clientState.hoveredMenuButton=id;playUiHoverSound()}}} onMouseLeave={()=>{if(clientState.hoveredMenuButton===id)clientState.hoveredMenuButton=''}} onMouseDown={()=>{playUiSelectSound();onMouseDown()}}/>}
  return <UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:1920,height:1080,zIndex:50,pointerFilter:'block'}} uiBackground={{texture:{src:'images/project-exodus-eliminated-menu.png'},textureMode:'stretch'}}>
    {hotspot('elim-continue',675,421,568,81,()=>requestRespawn('continue'))}
    {hotspot('elim-restart',675,517,568,77,()=>requestRespawn('rejoin'))}
    {hotspot('elim-outpost',675,609,568,77,()=>requestRespawn('outpost'))}
    {hotspot('elim-spectate',675,703,568,77,()=>clientState.eliminationDismissed=true)}
    {!solo&&<Label value="RESTART MISSION" fontSize={1} color={Color4.fromHexString('#ffffff00')} uiTransform={{positionType:'absolute',position:{left:675,top:517},width:568,height:77,zIndex:51,pointerFilter:'none'}}/>}
  </UiEntity>
}

const BADGES=[
['FIRST STEPS','Complete your first Project Exodus mission.','missionsCompleted',1],
['SCAVENGER','Loot 50 items. Every individual pickup counts.','lootCollected',50],
['SUPPLIER','Deliver supplies to the Outpost through supply objectives.','suppliesDelivered',10],
['CLEAN SWEEP','Complete a mission after eliminating every required enemy.','cleanSweeps',1],
['OUTPOST HERO','Complete the Outpost objective / defense mission.','outpostDefenses',1],
['PLANT RUNNER','Complete the Plant objective.','missionType',3],
['DOCKS DEALER','Complete the Docks objective.','missionType',4],
['ARENA CHAMPION','Complete the Arena objective.','missionType',5],
['EXPLORER','Discover all 8 named Project Exodus locations.','locations',8],
['LOOT MASTER','Collect all rare loot rewards: find 5 legendary/rare loot drops.','legendaryLoot',5],
['DRONE HUNTER','Eliminate 50 Drones.','droneKills',50],
['MUTANT SLAYER','Eliminate 50 Mutants.','mutantKills',50],
['SHARPSHOOTER','Land 100 confirmed headshots on hostile targets.','headshots',100],
['SURVIVOR','Use 100 medkits.','medkitsUsed',100],
['EXPLOSIVE EXPERT','Use 50 bombs or explosives during combat.','explosivesUsed',50],
['AMMO COLLECTOR','Pick up a total of 500 ammunition rounds.','ammoRoundsCollected',500],
['GEAR MASTER','Collect every gear type at least once.','gearTypes',8],
['EXPLORER','Discover all 8 named Project Exodus locations.','locations',8],
['LOOT CHAMPION','Collect at least one rare / legendary loot reward.','legendaryLoot',1],
['MISSION MASTER','Complete all 10 Project Exodus mission types.','missionTypes',10],
['LEGENDARY LOOTER','Find 5 legendary loot rewards. A legendary reward is discovered every 25th pickup.','legendaryLoot',5],
['GEAR COLLECTOR','Collect 100 weapon/ammunition gear pickups.','weaponsCollected',100],
['SCOUT MASTER','Discover all 8 named locations on the Project Exodus map.','locations',8],
['LOOT LEGEND','Collect 500 individual loot pickups.','lootCollected',500],
['MISSION SPECIALIST','Complete all 10 unique mission types at least once.','missionTypes',10],
['SPEED RUNNER','Complete a mission in under 5 minutes.','speedRuns',1],
['NIGHT OPS','Complete a mission during the night cycle.','nightMissions',1],
['LONE WOLF','Complete 10 solo missions.','soloMissions',10],
['TEAM PLAYER','Complete 10 co-op missions with other survivors.','coopMissions',10],
['EXODUS ELITE','Unlock all 29 previous Project Exodus badges.','all',29]
] as const
function bitCount(n:number){let c=0;for(let v=n>>>0;v;v>>>=1)c+=v&1;return c}
function badgeProgress(p:any,b:any): number{if(!p)return 0;if(b[2]==='all')return BADGES.slice(0,29).filter(x=>badgeProgress(p,x)>=x[3]).length;if(b[2]==='locations')return bitCount(Number(p.locationsDiscovered??0));if(b[2]==='missionTypes')return bitCount(Number(p.missionTypesMask??0)&1023);if(b[2]==='gearTypes')return bitCount(Number(p.gearTypesMask??0)&255);if(b[2]==='missionType')return (Number(p.missionTypesMask??0)&(1<<(Number(b[3])-1)))?Number(b[3]):0;return Math.max(0,Number(p[b[2]]??0))}
function badgeCollection(){
 if(!clientState.badgesOpen)return null
 const p:any=getLocalPlayerState(),earned=BADGES.filter(b=>badgeProgress(p,b)>=b[3]).length,sel=BADGES[Math.max(0,Math.min(29,clientState.selectedBadge))],prog=badgeProgress(p,sel),unlocked=prog>=sel[3]
 const cols=6,cellW=149,cellH=132,startX=72,startY=164
 const selectedPct=Math.max(0,Math.min(100,Math.round(prog/Math.max(1,Number(sel[3]))*100)))
 return <UiEntity uiTransform={{positionType:'absolute',position:{left:'50%',top:'50%'},margin:'-480px 0 0 -710px',width:1420,height:960,zIndex:100,pointerFilter:'block'}} uiBackground={{color:Color4.fromHexString('#00000000')}}>
   <UiEntity uiTransform={{positionType:'absolute',position:{left:20,top:20},width:1380,height:920,zIndex:100,pointerFilter:'none'}} uiBackground={{color:Color4.fromHexString('#24282eff')}}/>
   <UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:1420,height:960,zIndex:101,pointerFilter:'none'}} uiBackground={{texture:{src:'images/achievement-database-frame.png'},textureMode:'stretch'}}/>
   <Label value="PROJECT EXODUS — ACHIEVEMENT DATABASE" fontSize={24} color={c.white} uiTransform={{positionType:'absolute',position:{left:74,top:61},width:820,height:42,zIndex:103}}/>
   <Label value={`${earned}/30`} fontSize={22} color={c.white} uiTransform={{positionType:'absolute',position:{left:1105,top:61},width:105,height:42,zIndex:103}}/>
   <Button value="CLOSE" fontSize={16} color={c.white} uiTransform={{positionType:'absolute',position:{left:1230,top:55},width:135,height:62,zIndex:106}} uiBackground={{color:Color4.fromHexString('#00000001')}} onMouseEnter={()=>playUiHoverSound()} onMouseDown={()=>{playUiSelectSound();clientState.badgesOpen=false}}/>
   {BADGES.map((b,i)=>{const col=i%cols,row=Math.floor(i/cols),x=startX+col*cellW,y=startY+row*cellH,v=badgeProgress(p,b),goal=Math.max(1,Number(b[3])),pct=Math.max(0,Math.min(100,Math.round(v/goal*100))),ok=v>=goal,hover=clientState.hoveredMenuButton===`badge-old-${i}`,src=`images/badges/badge-${String(i+1).padStart(2,'0')}${ok?'':'-locked'}.png`;return <UiEntity uiTransform={{positionType:'absolute',position:{left:x,top:y},width:118,height:116,zIndex:103}}><UiEntity uiTransform={{positionType:'absolute',position:{left:14,top:2},width:90,height:82,pointerFilter:'none'}} uiBackground={{texture:{src},textureMode:'stretch'}}/><UiEntity uiTransform={{positionType:'absolute',position:{left:8,top:82},width:102,height:6,pointerFilter:'none'}} uiBackground={{color:Color4.fromHexString('#34393eff')}}><UiEntity uiTransform={{width:`${pct}%`,height:6,pointerFilter:'none'}} uiBackground={{color:ok?c.green:c.red}}/></UiEntity><Label value={`${String(i+1).padStart(2,'0')}  ${pct}%  ${Math.min(v,goal)}/${goal}`} fontSize={7} color={hover||i===clientState.selectedBadge?c.amber:c.white} uiTransform={{positionType:'absolute',position:{left:3,top:91},width:112,height:14,pointerFilter:'none'}}/><Button value="" uiTransform={{positionType:'absolute',position:{left:0,top:0},width:118,height:116,zIndex:105}} uiBackground={{color:Color4.fromHexString('#00000001')}} onMouseEnter={()=>{clientState.hoveredMenuButton=`badge-old-${i}`;playUiHoverSound()}} onMouseLeave={()=>{if(clientState.hoveredMenuButton===`badge-old-${i}`)clientState.hoveredMenuButton=''}} onMouseDown={()=>{playUiSelectSound();clientState.selectedBadge=i}}/></UiEntity>})}
   <Label value={unlocked?'◇ 3D HOLOGRAM — UNLOCKED ◇':'◇ 3D HOLOGRAM — LOCKED ◇'} fontSize={12} color={unlocked?c.cyan:c.muted} uiTransform={{positionType:'absolute',position:{left:1044,top:204},width:318,height:22,zIndex:103}}/>
   <UiEntity uiTransform={{positionType:'absolute',position:{left:1074,top:236},width:255,height:255,zIndex:103,pointerFilter:'none'}} uiBackground={{texture:{src:`images/badges/badge-${String(clientState.selectedBadge+1).padStart(2,'0')}${unlocked?'':'-locked'}.png`},textureMode:'stretch'}}/>
   <Label value={`${String(clientState.selectedBadge+1).padStart(2,'0')} — ${sel[0]}`} fontSize={15} color={unlocked?c.cyan:c.white} uiTransform={{positionType:'absolute',position:{left:1046,top:548},width:316,height:38,zIndex:103}}/>
   <Label value={`OBJECTIVE\n${sel[1]}`} fontSize={12} color={c.white} uiTransform={{positionType:'absolute',position:{left:1048,top:600},width:312,height:58,zIndex:103}}/>
   <Label value={`PROGRESS   ${Math.min(prog,Number(sel[3]))} / ${sel[3]}   (${selectedPct}%)`} fontSize={12} color={c.white} uiTransform={{positionType:'absolute',position:{left:1048,top:660},width:312,height:20,zIndex:103}}/>
   <UiEntity uiTransform={{positionType:'absolute',position:{left:1048,top:684},width:312,height:10,zIndex:103}} uiBackground={{color:Color4.fromHexString('#34393eff')}}><UiEntity uiTransform={{width:`${selectedPct}%`,height:10}} uiBackground={{color:unlocked?c.green:c.red}}/></UiEntity>
   <Label value={`Complete the exact objective above to activate this badge.\n\nCAMPAIGN + REPLAY OPERATIONS\nAll 30 achievements are gameplay-obtainable.`} fontSize={9} color={c.white} uiTransform={{positionType:'absolute',position:{left:1048,top:710},width:312,height:62,zIndex:103}}/>
 </UiEntity>
}
function scopeOverlay(){if(!clientState.scopeToggled)return null;const p=getLocalPlayerState();if(p?.equippedWeapon==='rail-pistol')return null;return <UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:'100%',height:'100%',zIndex:90,pointerFilter:'none'}} uiBackground={{texture:{src:'images/scope-overlay.png'},textureMode:'stretch'}}><Label value="5x ZOOM" fontSize={18} color={c.red} uiTransform={{positionType:'absolute',position:{right:70,top:52},width:130,height:34}}/><Button value="EXIT SCOPE" fontSize={16} color={c.white} uiTransform={{positionType:'absolute',position:{right:45,bottom:45},width:180,height:48,borderColor:c.line,borderWidth:2,pointerFilter:'block'}} uiBackground={{color:c.red}} onMouseDown={toggleScope}/></UiEntity>}


function memoryPickup(){if(!clientState.memoryPickupActive)return null;const pct=Math.round(clientState.memoryPickupProgress*100),sec=Math.min(10,Math.floor(clientState.memoryPickupProgress*10));const memory=clientState.memoryPickupKind==='memory';return <UiEntity uiTransform={{positionType:'absolute',position:{left:'50%',bottom:118},margin:'0 0 0 -210px',width:440,height:100,padding:'18px 22px 12px 22px',flexDirection:'column',borderWidth:0,zIndex:35}} uiBackground={{color:Color4.fromHexString('#08090bf2')}}><UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:440,height:100,zIndex:36,pointerFilter:'none'}} uiBackground={{texture:{src:memory?'images/ui/exodus-expanded/memory-loading-frame.png':'images/ui/exodus-expanded/data-loading-frame.png'},textureMode:'stretch'}}/><Label value={`${memory?'MEMORY PACK':'DATA RAM'} — COLLECTING ${sec}/10s`} fontSize={15} color={memory?c.red:c.cyan} uiTransform={{width:396,height:28}}/><UiEntity uiTransform={{width:396,height:16,borderColor:memory?c.red:c.blue,borderWidth:1}} uiBackground={{color:c.soft}}><UiEntity uiTransform={{width:`${pct}%`,height:16}} uiBackground={{color:memory?c.red:c.blue}}/></UiEntity></UiEntity>}

function memoryStoryPopup(){
 if(!clientState.memoryStoryOpen)return null
 const index=Math.max(1,clientState.memoryStoryIndex)
  const memoryPackPages:Record<number,string[]>={
  1:['images/story/memory-packs/memory-pack-01-01.jpg','images/story/memory-packs/memory-pack-01-02.jpg','images/story/memory-packs/memory-pack-01-03.jpg','images/story/memory-packs/memory-pack-01-04.jpg','images/story/memory-packs/memory-pack-01-05.jpg','images/story/memory-packs/memory-pack-01-06.jpg'],
  2:['images/story/memory-packs/memory-pack-02-01.jpg','images/story/memory-packs/memory-pack-02-02.jpg','images/story/memory-packs/memory-pack-02-03.jpg','images/story/memory-packs/memory-pack-02-04.jpg','images/story/memory-packs/memory-pack-02-05.jpg','images/story/memory-packs/memory-pack-02-06.jpg'],
  3:['images/story/memory-packs/memory-pack-03-01.jpg','images/story/memory-packs/memory-pack-03-02.jpg','images/story/memory-packs/memory-pack-03-03.jpg','images/story/memory-packs/memory-pack-03-04.jpg','images/story/memory-packs/memory-pack-03-05.jpg','images/story/memory-packs/memory-pack-03-06.jpg','images/story/memory-packs/memory-pack-03-07.jpg'],
  4:['images/story/memory-packs/memory-pack-04-01.jpg','images/story/memory-packs/memory-pack-04-02.jpg','images/story/memory-packs/memory-pack-04-03.jpg','images/story/memory-packs/memory-pack-04-04.jpg','images/story/memory-packs/memory-pack-04-05.jpg','images/story/memory-packs/memory-pack-04-06.jpg'],
  5:['images/story/memory-packs/memory-pack-05-01.jpg','images/story/memory-packs/memory-pack-05-02.jpg','images/story/memory-packs/memory-pack-05-03.jpg','images/story/memory-packs/memory-pack-05-04.jpg','images/story/memory-packs/memory-pack-05-05.jpg','images/story/memory-packs/memory-pack-05-06.jpg'],
  6:['images/story/memory-packs/memory-pack-06-01.jpg','images/story/memory-packs/memory-pack-06-02.jpg','images/story/memory-packs/memory-pack-06-03.jpg','images/story/memory-packs/memory-pack-06-04.jpg','images/story/memory-packs/memory-pack-06-05.jpg','images/story/memory-packs/memory-pack-06-06.jpg'],
  7:['images/story/memory-packs/memory-pack-07-01.jpg','images/story/memory-packs/memory-pack-07-02.jpg','images/story/memory-packs/memory-pack-07-03.jpg','images/story/memory-packs/memory-pack-07-04.jpg','images/story/memory-packs/memory-pack-07-05.jpg','images/story/memory-packs/memory-pack-07-06.jpg'],
  8:['images/story/memory-packs/memory-pack-08-01.jpg','images/story/memory-packs/memory-pack-08-02.jpg','images/story/memory-packs/memory-pack-08-03.jpg','images/story/memory-packs/memory-pack-08-04.jpg','images/story/memory-packs/memory-pack-08-05.jpg','images/story/memory-packs/memory-pack-08-06.jpg'],
  9:['images/story/memory-packs/memory-pack-09-01.jpg','images/story/memory-packs/memory-pack-09-02.jpg','images/story/memory-packs/memory-pack-09-03.jpg','images/story/memory-packs/memory-pack-09-04.jpg','images/story/memory-packs/memory-pack-09-05.jpg'],
  10:['images/story/memory-packs/memory-pack-10-01.jpg','images/story/memory-packs/memory-pack-10-02.jpg','images/story/memory-packs/memory-pack-10-03.jpg','images/story/memory-packs/memory-pack-10-04.jpg','images/story/memory-packs/memory-pack-10-05.jpg'],
 }
 const pages=memoryPackPages[index]??[]
 const page=Math.min(clientState.memoryStoryPage,Math.max(0,pages.length-1)),hasNext=page<pages.length-1
 return <UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:'100%',height:'100%',alignItems:'center',justifyContent:'center',zIndex:170,pointerFilter:'block'}} uiBackground={{color:Color4.fromHexString('#000000f4')}}><UiEntity uiTransform={{width:1600,height:900,positionType:'relative',borderColor:c.red,borderWidth:2}}>{pages.length>0&&<UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:1600,height:900,zIndex:170}} uiBackground={{texture:{src:pages[page]},textureMode:'stretch'}}/>}{clientState.hoveredMenuButton==='memory-continue'&&<UiEntity uiTransform={{positionType:'absolute',position:{left:618,bottom:20},width:365,height:76,zIndex:172,pointerFilter:'none'}} uiBackground={{texture:{src:'images/ui/memory-continue-hover.png'},textureMode:'stretch'}}/>}<Button value="" fontSize={1} color={Color4.fromHexString('#ffffff00')} uiTransform={{positionType:'absolute',position:{left:618,bottom:20},width:365,height:76,borderWidth:0,zIndex:173}} uiBackground={{color:Color4.fromHexString('#00000001')}} onMouseEnter={()=>{clientState.hoveredMenuButton='memory-continue';playUiHoverSound()}} onMouseLeave={()=>{if(clientState.hoveredMenuButton==='memory-continue')clientState.hoveredMenuButton=''}} onMouseDown={()=>{playUiSelectSound();if(hasNext)clientState.memoryStoryPage+=1;else{clientState.memoryStoryOpen=false;clientState.memoryStoryPage=0;setStoryMusic(false)}}}/></UiEntity></UiEntity>
}

function cinematicOverlay(){if(!clientState.cinematicActive)return null;return <UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:1920,height:1080,zIndex:200,pointerFilter:'block'}} uiBackground={{color:Color4.fromHexString('#00000001')}}><Button value="[ F ]  SKIP CINEMATIC" fontSize={18} color={c.white} uiTransform={{positionType:'absolute',position:{right:52,bottom:48},width:290,height:58,borderColor:c.white,borderWidth:2,zIndex:203}} uiBackground={{color:Color4.fromHexString('#080b0ecc')}} onMouseDown={finishIntroCinematic}/></UiEntity>}
function dataStoryPopup(){
 if(!clientState.dataStoryOpen)return null
 const index=Math.max(1,clientState.dataStoryIndex)
 const dataRamPages:Record<number,string[]>={
 1:['images/story/data-rams/data-ram-01-01.jpg','images/story/data-rams/data-ram-01-02.jpg'],
 2:['images/story/data-rams/data-ram-02-01.jpg'],3:['images/story/data-rams/data-ram-03-01.jpg'],4:['images/story/data-rams/data-ram-04-01.jpg'],
 5:['images/story/data-rams/data-ram-05-01.jpg'],6:['images/story/data-rams/data-ram-06-01.jpg'],7:['images/story/data-rams/data-ram-07-01.jpg'],
 8:['images/story/data-rams/data-ram-08-01.jpg'],9:['images/story/data-rams/data-ram-09-01.jpg'],
 10:['images/story/data-rams/data-ram-10-01.jpg','images/story/data-rams/data-ram-10-02.jpg','images/story/data-rams/data-ram-10-03.jpg'],
 11:['images/story/data-rams/data-ram-11-01.jpg'],12:['images/story/data-rams/data-ram-12-01.jpg','images/story/data-rams/data-ram-12-02.jpg'],
 13:['images/story/data-rams/data-ram-13-01.jpg','images/story/data-rams/data-ram-13-02.jpg','images/story/data-rams/data-ram-13-03.jpg'],
 14:['images/story/data-rams/data-ram-14-01.jpg','images/story/data-rams/data-ram-14-02.jpg','images/story/data-rams/data-ram-14-03.jpg','images/story/data-rams/data-ram-14-04.jpg']
 }
 const pages=dataRamPages[index]??[]
 const page=Math.min(clientState.dataStoryPage,Math.max(0,pages.length-1)),hasNext=page<pages.length-1
 return <UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:'100%',height:'100%',zIndex:170,alignItems:'center',justifyContent:'center',pointerFilter:'block'}} uiBackground={{color:Color4.fromHexString('#000000f4')}}><UiEntity uiTransform={{width:1600,height:900,positionType:'relative',borderColor:c.cyan,borderWidth:2}}>{pages.length>0&&<UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:1600,height:900,zIndex:170}} uiBackground={{texture:{src:pages[page]},textureMode:'stretch'}}/>}{clientState.hoveredMenuButton==='data-continue'&&<UiEntity uiTransform={{positionType:'absolute',position:{left:618,bottom:20},width:365,height:76,zIndex:172,pointerFilter:'none'}} uiBackground={{texture:{src:'images/ui/data-continue-hover.png'},textureMode:'stretch'}}/>}<Button value="" fontSize={1} color={Color4.fromHexString('#ffffff00')} uiTransform={{positionType:'absolute',position:{left:618,bottom:20},width:365,height:76,borderWidth:0,zIndex:173}} uiBackground={{color:Color4.fromHexString('#00000001')}} onMouseEnter={()=>{clientState.hoveredMenuButton='data-continue';playUiHoverSound()}} onMouseLeave={()=>{if(clientState.hoveredMenuButton==='data-continue')clientState.hoveredMenuButton=''}} onMouseDown={()=>{playUiSelectSound();if(hasNext)clientState.dataStoryPage+=1;else{clientState.dataStoryOpen=false;clientState.dataStoryPage=0;setStoryMusic(false)}}}/></UiEntity></UiEntity>
}

function gameplayFrame(){const player=getLocalPlayerState();if(player&&!player.alive&&!clientState.eliminationDismissed)return null;const frame=clientState.isMobile?'images/ui/project-exodus-mobile-gameplay-frame.png':'images/ui/project-exodus-gameplay-frame.png';return <UiEntity uiTransform={{positionType:'absolute',position:{left:0,top:0},width:1920,height:1080,zIndex:60,pointerFilter:'none'}} uiBackground={{texture:{src:frame},textureMode:'stretch'}}/>}

function alphaTestLabel(){return <Label value="Alpha Test v0. 00" fontSize={16} color={c.white} uiTransform={{positionType:'absolute',position:{right:18,bottom:14},width:180,height:28,zIndex:165,pointerFilter:'none'}}/>}

function hud(){if(clientState.welcomeOpen)return <UiEntity uiTransform={{width:'100%',height:'100%',pointerFilter:'none'}}>{welcomeScreen()}</UiEntity>;if(clientState.cinematicActive)return <UiEntity uiTransform={{width:'100%',height:'100%',pointerFilter:'none'}}>{cinematicOverlay()}</UiEntity>;const active=!clientState.insideOutpost;return <UiEntity uiTransform={{width:'100%',height:'100%',pointerFilter:'none'}}>{active&&compass()}{minimap()}{active&&mission()}{active&&matchInfo()}{active&&survival()}{active&&ammo()}{active&&quickbar()}{active&&!clientState.isMobile&&controls()}{active&&gameplayFrame()}{active&&!clientState.aiming&&crosshair()}{controlsOverlay()}{badgeCollection()}{memoryPickup()}{memoryStoryPopup()}{dataStoryPopup()}{missionCompleteBanner()}{active&&!clientState.isMobile&&build()}{active&&mobile()}{active&&enemyTarget()}{active&&droneAlert()}{active&&damageIndicator()}{inventory()}{shop()}{missionTerminal()}{fullMap()}{note()}{lobby()}{!clientState.insideOutpost&&elimination()}{scopeOverlay()}{alphaTestLabel()}</UiEntity>}
export function setupUi(){ReactEcsRenderer.setUiRenderer(hud,{virtualWidth:1920,virtualHeight:1080,screenInset:'device'})}
